
name: Rain Alert

on:
  schedule:
    - cron: "30 1 * * *"

  workflow_dispatch:

jobs:
  rain-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run rain alert
        env:
          PASSWD: ${{ secrets.MY_PASSWORD}}
          EMAIL: ${{ secrets.MY_EMAIL }}
          API_KEY: ${{ secrets.WEATHER_API }}
        run: python rain_alert.py
